package(default_visibility = ["//visibility:public"])

android_library(
    name = "MainActivity",
    srcs = [
        "MainActivity.java",
    ],
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
)
