package(default_visibility = ["//visibility:public"])

android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    visibility = ["__pkg__"],
    deps = ["//app/src/main/java/com/ranaaditya/bazel_build:MainActivity"],
)
